/**
 * This file is autogenerated by Scaffold-Stark.
 * You should not edit it manually or your changes might be overwritten.
 */

const deployedContracts = {
  devnet: {
    StakingContract: {
      address:
        "0x64c7ae2365e58c6205d53c07bebbc47b45d3cabc38a21d067dcf0e42672588e",
      abi: [
        {
          type: "impl",
          name: "StakingContractImpl",
          interface_name: "contracts::staking_dapp::IStakingContract",
        },
        {
          type: "enum",
          name: "core::bool",
          variants: [
            {
              name: "False",
              type: "()",
            },
            {
              name: "True",
              type: "()",
            },
          ],
        },
        {
          type: "interface",
          name: "contracts::staking_dapp::IStakingContract",
          items: [
            {
              type: "function",
              name: "set_allowed_tokens",
              inputs: [
                {
                  name: "token_address",
                  type: "core::starknet::contract_address::ContractAddress",
                },
              ],
              outputs: [
                {
                  type: "core::bool",
                },
              ],
              state_mutability: "external",
            },
            {
              type: "function",
              name: "remove_allowed_token",
              inputs: [
                {
                  name: "token_address",
                  type: "core::starknet::contract_address::ContractAddress",
                },
              ],
              outputs: [
                {
                  type: "core::bool",
                },
              ],
              state_mutability: "external",
            },
            {
              type: "function",
              name: "set_reward_rate",
              inputs: [
                {
                  name: "rate",
                  type: "core::integer::u128",
                },
              ],
              outputs: [
                {
                  type: "core::bool",
                },
              ],
              state_mutability: "external",
            },
          ],
        },
        {
          type: "constructor",
          name: "constructor",
          inputs: [
            {
              name: "initial_reward_rate",
              type: "core::integer::u128",
            },
          ],
        },
        {
          type: "event",
          name: "contracts::staking_dapp::StakingContract::Event",
          kind: "enum",
          variants: [],
        },
      ],
      classHash:
        "0x2a6da08c8c73d52b9e8a2d04ce8359b8790760d35c0dc2b72095c5b61da29c0",
    },
  },
} as const;

export default deployedContracts;
