/**
 * This file is autogenerated by Scaffold-Stark.
 * You should not edit it manually or your changes might be overwritten.
 */

const deployedContracts = {
  devnet: {
    StakingContract: {
      address:
        "0x4b8a210a93f0ad94d6fe27997c97ec213fecc383e7872c2fe01d713c66b0fd7",
      abi: [
        {
          type: "impl",
          name: "StakingContractImpl",
          interface_name: "contracts::staking_dapp::IStakingContract",
        },
        {
          type: "enum",
          name: "core::bool",
          variants: [
            {
              name: "False",
              type: "()",
            },
            {
              name: "True",
              type: "()",
            },
          ],
        },
        {
          type: "interface",
          name: "contracts::staking_dapp::IStakingContract",
          items: [
            {
              type: "function",
              name: "set_allowed_tokens",
              inputs: [
                {
                  name: "token_address",
                  type: "core::starknet::contract_address::ContractAddress",
                },
              ],
              outputs: [
                {
                  type: "core::bool",
                },
              ],
              state_mutability: "external",
            },
          ],
        },
        {
          type: "constructor",
          name: "constructor",
          inputs: [],
        },
        {
          type: "event",
          name: "contracts::staking_dapp::StakingContract::Event",
          kind: "enum",
          variants: [],
        },
      ],
      classHash:
        "0xc1afac9cb89b9d4557e8727711ef321616ebcf82ec295acf59dcbd109b29e1",
    },
  },
} as const;

export default deployedContracts;
